name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.repository.is_template != true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Install to instance
        env:
          SN_SDK_NODE_ENV: SN_SDK_CI_INSTALL
          SN_SDK_AUTH_TYPE: basic
          SN_SDK_USER: ${{ secrets.SN_SDK_USER }}
          SN_SDK_USER_PWD: ${{ secrets.SN_SDK_USER_PWD }}
          SN_SDK_INSTANCE_URL: ${{ secrets.SN_SDK_INSTANCE_URL }}
        run: pnpm run install:instance
