name: Sync from template

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    if: github.event.repository.is_template != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: AndreasAugustin/actions-template-sync@8a0f668b83c32a0f673353086d74f12b8853d4f5 # v2.5.3
        with:
          source_repo_path: h13/servicenow-app-template
          upstream_branch: main
          pr_title: 'chore: sync from servicenow-app-template'
          pr_labels: template-sync
